# Generated by Django 4.0.3 on 2022-05-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('offer', models.TextField()),
                ('price', models.TextField()),
                ('delivery', models.TextField()),
                ('support', models.TextField()),
                ('recommend', models.TextField()),
                ('change', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
